using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FitRaspi
{
    class Cl_Athlete
    {
        // Bitte Klassen Properties anlegen
        private string name;
        private string firstname;
        //...
        //...
        //...
        //...
        //...
        //...

        // Bitte Konstruktor bauen ;)
        public Cl_Athlete(/*...*/)
        {
                
                //bla...
                //bla...
                //bla...
                //bla...
                //bla...
                //bla...
        }

        public double calc_kfa()
        {
            return (0);
        }

    }
}
